<?php return array(
    'root' => array(
        'name' => 'drupal/recommended-project',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'ajgl/breakpoint-twig-extension' => array(
            'pretty_version' => '0.3.5',
            'version' => '0.3.5.0',
            'reference' => '9875feea0ac4bc3c9f308c62bae4727669d6052a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ajgl/breakpoint-twig-extension',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'arthurkushman/query-path' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.1.4',
            ),
        ),
        'asm89/stack-cors' => array(
            'pretty_version' => 'v2.2.0',
            'version' => '2.2.0.0',
            'reference' => '50f57105bad3d97a43ec4a485eb57daf347eafea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../asm89/stack-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chi-teck/drupal-code-generator' => array(
            'pretty_version' => '3.6.1',
            'version' => '3.6.1.0',
            'reference' => '2dbd8d231945681a398862a3282ade3cf0ea23ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chi-teck/drupal-code-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '12fb2dfe5e16183de69e784a7b84046c43d97e8e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.4.2',
            'version' => '3.4.2.0',
            'reference' => 'c51258e759afdb17f1fd1fe83bc12baaef6309d6',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/annotated-command' => array(
            'pretty_version' => '4.10.0',
            'version' => '4.10.0.0',
            'reference' => '1e830ba908c9ffb1ba7ca056203531b27188812c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/annotated-command',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/config' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'reference' => '597f8d7fbeef801736250ec10c3e190569b1b0ae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/filter-via-dot-access-data' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'cb2eeba41f8e2e3c61698a5cf70ef048ff6c9d5b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/filter-via-dot-access-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/log' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'c27a3beb36137c141ccbce0d89f64befb243c015',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/output-formatters' => array(
            'pretty_version' => '4.5.0',
            'version' => '4.5.0.0',
            'reference' => '7a611b01eb48eb19cd54672339fc08c0985bf540',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/output-formatters',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/robo' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => '55a272370940607649e5c46eb173c5c54f7c166d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/robo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/self-update' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '972a1016761c9b63314e040836a12795dff6953a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/self-update',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/site-alias' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => '1056ceb93f6aafe6f7600d7bbe1b62b8488abccf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-alias',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/site-process' => array(
            'pretty_version' => '5.4.0',
            'version' => '5.4.0.0',
            'reference' => '7ab3ffe4195a89b8dc334ea22e7881abe79ffd9a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cweagans/composer-patches' => array(
            'pretty_version' => '1.7.3',
            'version' => '1.7.3.0',
            'reference' => 'e190d4466fe2b103a55467dfa83fc2fecfcaf2db',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../cweagans/composer-patches',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'a23a2bf4f31d3518f3ecb38660c95715dfead60f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '1.14.3',
            'version' => '1.14.3.0',
            'reference' => 'fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/common' => array(
            'pretty_version' => '3.4.4',
            'version' => '3.4.4.0',
            'reference' => '0aad4b7ab7ce8c6602dfbb1e1a24581275fb9d1a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/common',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'dfbaa3c2d2e9a9df1118213f3b8b0c597bb99fab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'b680156fa328f1dfd874fd48c7026c41570b9c6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '861c870e8b75f7c8f69c146c7f89cc1c0f1b49b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '3.3.3',
            'version' => '3.3.3.0',
            'reference' => 'b337726451f5d530df338fc7f68dee8781b49779',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/admin_toolbar' => array(
            'pretty_version' => '3.4.2',
            'version' => '3.4.2.0',
            'reference' => '3.4.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/admin_toolbar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/captcha' => array(
            'pretty_version' => '2.0.6',
            'version' => '2.0.6.0',
            'reference' => '2.0.6',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/captcha',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/chosen' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => '4.0.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/chosen',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/chosen_lib' => array(
            'pretty_version' => '4.0.1',
            'version' => '4.0.1.0',
            'reference' => null,
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/ckeditor_codemirror' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '3.0.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/ckeditor_codemirror',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core' => array(
            'pretty_version' => '10.3.1',
            'version' => '10.3.1.0',
            'reference' => 'd137403a30d4154404e473785f48dfc889d77e23',
            'type' => 'drupal-core',
            'install_path' => __DIR__ . '/../../html/core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-annotation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-assertion' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-class-finder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-composer-scaffold' => array(
            'pretty_version' => '10.3.1',
            'version' => '10.3.1.0',
            'reference' => 'a1a186caeb89899143e0c6912ccee9d3d7181dbe',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-composer-scaffold',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-datetime' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-dependency-injection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-diff' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-discovery' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-event-dispatcher' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-file-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-file-security' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-front-matter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-gettext' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-graph' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-http-foundation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-php-storage' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-plugin' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-project-message' => array(
            'pretty_version' => '10.3.1',
            'version' => '10.3.1.0',
            'reference' => 'd1da83722735cb0f7ccabf9fef7b5607b442c3a8',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-project-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-proxy-builder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-recommended' => array(
            'pretty_version' => '10.3.1',
            'version' => '10.3.1.0',
            'reference' => 'a5183f2be315b7e5deec89fdeafe9fc9a2e54f57',
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-render' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-serialization' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-transliteration' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-utility' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/core-version' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '10.3.1',
            ),
        ),
        'drupal/cshs' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'reference' => '4.0.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/cshs',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/devel' => array(
            'pretty_version' => '5.2.1',
            'version' => '5.2.1.0',
            'reference' => '5.2.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/devel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/devel_kint_extras' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => '1.1.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/devel_kint_extras',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/eck' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '2.0.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/eck',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/entity_reference_revisions' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '8.x-1.11',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/entity_reference_revisions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/feeds' => array(
            'pretty_version' => '3.0.0-beta5',
            'version' => '3.0.0.0-beta5',
            'reference' => '8.x-3.0-beta5',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/feeds',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/feeds_ex' => array(
            'pretty_version' => '1.0.0-beta4',
            'version' => '1.0.0.0-beta4',
            'reference' => '8.x-1.0-beta4',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/feeds_ex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/feeds_para_mapper' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '8.x-1.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/feeds_para_mapper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/feeds_tamper' => array(
            'pretty_version' => '2.0.0-beta3',
            'version' => '2.0.0.0-beta3',
            'reference' => '8.x-2.0-beta3',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/feeds_tamper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/inline_entity_form' => array(
            'pretty_version' => '3.0.0-rc19',
            'version' => '3.0.0.0-RC19',
            'reference' => '3.0.0-rc19',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/inline_entity_form',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/jquery_ui' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => '8.x-1.7',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/jquery_ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/lang_dropdown' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '8.x-2.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/lang_dropdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/language_hierarchy' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '2.0.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/language_hierarchy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/menu_block' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '8.x-1.11',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/menu_block',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate_devel' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '8.x-2.3',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/migrate_devel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate_manifest' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '3.1.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/migrate_manifest',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate_plus' => array(
            'pretty_version' => '6.0.4',
            'version' => '6.0.4.0',
            'reference' => '6.0.4',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/migrate_plus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate_tools' => array(
            'pretty_version' => '6.0.4',
            'version' => '6.0.4.0',
            'reference' => '6.0.4',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/migrate_tools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate_upgrade' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'reference' => '4.0.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/migrate_upgrade',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migration_tools' => array(
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => '8.x-2.8',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/migration_tools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/paragraphs' => array(
            'pretty_version' => '1.17.0',
            'version' => '1.17.0.0',
            'reference' => '8.x-1.17',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/paragraphs',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/php' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '8.x-1.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/recommended-project' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/redirect' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'reference' => '8.x-1.9',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/redirect',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/tamper' => array(
            'pretty_version' => '1.0.0-alpha4',
            'version' => '1.0.0.0-alpha4',
            'reference' => '8.x-1.0-alpha4',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/tamper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/tocify' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '3.1.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/tocify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/twbstools' => array(
            'pretty_version' => 'dev-2.1.x',
            'version' => 'dev-2.1.x',
            'reference' => 'cbd2730d5e8f2149e79d7300a421a147bec37356',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/twbstools',
            'aliases' => array(
                0 => '2.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'drupal/twig_vardumper' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => '3.1.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/twig_vardumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/twig_xdebug' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '8.x-1.3',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/twig_xdebug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/views_bulk_operations' => array(
            'pretty_version' => '4.2.7',
            'version' => '4.2.7.0',
            'reference' => '4.2.7',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/views_bulk_operations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/views_migration' => array(
            'pretty_version' => '1.2.7',
            'version' => '1.2.7.0',
            'reference' => '1.2.7',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/views_migration',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/webform' => array(
            'pretty_version' => '6.2.7',
            'version' => '6.2.7.0',
            'reference' => '6.2.7',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/webform',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/webform_migrate' => array(
            'pretty_version' => '2.0.0-alpha1',
            'version' => '2.0.0.0-alpha1',
            'reference' => '2.0.0-alpha1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/webform_migrate',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/webform_node' => array(
            'pretty_version' => '6.2.7',
            'version' => '6.2.7.0',
            'reference' => null,
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/webform_validation' => array(
            'pretty_version' => '2.0.0-rc2',
            'version' => '2.0.0.0-RC2',
            'reference' => '2.0.0-rc2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../html/modules/contrib/webform_validation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drush/drush' => array(
            'pretty_version' => '12.5.2',
            'version' => '12.5.2.0',
            'reference' => '4aebed85dc818ff762f2e24a85b023d2a52050df',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drush/drush',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '4.0.2',
            'version' => '4.0.2.0',
            'reference' => 'ebaaf5be6c0286928352e054f2d5125608e5405e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'flow/jsonpath' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'grasmash/expander' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'bb1c1a2430957945cf08c5a62f5d72a6aa6a2c82',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/expander',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'grasmash/yaml-cli' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '09a8860566958a1576cc54bbe910a03477e54971',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/yaml-cli',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'gravitypdf/querypath' => array(
            'pretty_version' => '3.2.3',
            'version' => '3.2.3.0',
            'reference' => 'e4b11dc1e713a405c8dee570c515affe9c04f232',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gravitypdf/querypath',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.8.2',
            'version' => '7.8.2.0',
            'reference' => 'f4152d9eb85c445fe1f992001d1748e8bec070d2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => '6ea8dd08867a2a42619d65c3deb2c0fcbf81c8f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.6.3',
            'version' => '2.6.3.0',
            'reference' => '6de29867b18790c0d2c846af4c13a24cc3ad56f3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jjj/chosen' => array(
            'pretty_version' => '2.2.1',
            'version' => '2.2.1.0',
            'reference' => '2.2.1',
            'type' => 'drupal-library',
            'install_path' => __DIR__ . '/../../html/libraries/chosen',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kint-php/kint' => array(
            'pretty_version' => '5.1.1',
            'version' => '5.1.1.0',
            'reference' => '8c5ec370c3382ceae0b88e91f9bbb00e6bb4f93b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kint-php/kint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-escaper' => array(
            'pretty_version' => '2.13.0',
            'version' => '2.13.0.0',
            'reference' => 'af459883f4018d0f8a0c69c7a209daef3bf973ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-escaper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-feed' => array(
            'pretty_version' => '2.22.0',
            'version' => '2.22.0.0',
            'reference' => '669792b819fca7274698147ad7a2ecc1b0a9b141',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-feed',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laminas/laminas-stdlib' => array(
            'pretty_version' => '3.19.0',
            'version' => '3.19.0.0',
            'reference' => '6a192dd0882b514e45506f533b833b623b78fff3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-stdlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/container' => array(
            'pretty_version' => '4.2.2',
            'version' => '4.2.2.0',
            'reference' => 'ff346319ca1ff0e78277dc2311a42107cc1aab88',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.9.0',
            'version' => '2.9.0.0',
            'reference' => 'f5ac2c0b0a2eefca70b2ce32a5809992227e75a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mck89/peast' => array(
            'pretty_version' => 'v1.16.3',
            'version' => '1.16.3.0',
            'reference' => '645ec21b650bc2aced18285c85f220d22afc1430',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mck89/peast',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mtdowling/jmespath.php' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'bbb69a935c2cbb0c03d7f481a238027430f6440b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/jmespath.php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.1.0',
            'version' => '5.1.0.0',
            'reference' => '683130c2ff8c2739f4822ff7ac5c873ec529abd1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orno/di' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'pear/archive_tar' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => 'b439c859564f5cbb0f64ad6002d0afe84a889602',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/archive_tar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.15',
            'version' => '1.10.15.0',
            'reference' => 'ce0adade8b97561656ace07cdaac4751c271ea8c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phootwork/collection' => array(
            'pretty_version' => 'v3.2.2',
            'version' => '3.2.2.0',
            'reference' => '46dde20420fba17766c89200bc3ff91d3e58eafa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phootwork/collection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phootwork/lang' => array(
            'pretty_version' => 'v3.2.2',
            'version' => '3.2.2.0',
            'reference' => 'baaf154ae7d521ebeee5e89105f5b12b0f234597',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phootwork/lang',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpowermove/docblock' => array(
            'pretty_version' => 'v4.0',
            'version' => '4.0.0.0',
            'reference' => 'a73f6e17b7d4e1b92ca5378c248c952c9fae7826',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpowermove/docblock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
                1 => '^1.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'fe5ea303b0887d5caefd3d431c3e61ad47037001',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.12.4',
            'version' => '0.12.4.0',
            'reference' => '2fd717afa05341b4f8152547f142cd2f130f6818',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'querypath/querypath' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.0.5',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.15',
            ),
        ),
        'sebastian/diff' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => 'ba01945089c3a293b01ba9badc29ad55b106b0bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'softcreatr/jsonpath' => array(
            'pretty_version' => '0.9.1',
            'version' => '0.9.1.0',
            'reference' => '272173a65fd16b25010dbd54d04dd34c0c5a8500',
            'type' => 'library',
            'install_path' => __DIR__ . '/../softcreatr/jsonpath',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '6edb5363ec0c78ad4d48c5128ebf4d083d89d3a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'a4df9dfe5da2d177af6643610c7bee2cb76a9f5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '0e0d29ce1f20deffb4ab1b016a7257c4f1e789a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'c9b7cc075b3ab484239855622ca05cb0b99c13ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '8d7507f02b06e06815e56bb39aa0128e3806208b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '8f93aec25d41b72493c6ddff14e916177c9efc50',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'b51ef8059159330b74a4d52f68e671033c0fe463',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '3ef977a43883215d560a2cecb82ec8e62131471c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '27de8cc95e11db7a50b027e71caaab9024545947',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'cc4a9bec6e1bdd2405f40277a68a6ed1bb393005',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mailer' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'e2d56f180f5b8c5e7c0fbea872bb1f529b6d6d45',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '7d048964877324debdcb4e0549becfa064a20d43',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'ef4d7e442ca910c4764bce785146269b30cb5fc4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'cd4226d140ecd3d0f13d32ed0a4a095ffe871d2f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => '32a9da87d7b3245e09ac426c83d334ae9f06f80f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'a287ed7475f85bf6f61890146edbc932c0fff919',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'bc45c394692b948b4d383a08d7753968bed9a83d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => '9773676c8a1bb1f8d4340a62efe641cf76eda7ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => '10112722600777e02d2745716b70c5db4ca70442',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => '77fa7995ac1b21ab60769b7323d600a991a90433',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => '3fb075789fb91f9ad9af537c4012d523085bd5af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => '86fcae159633351e5fd145d1c47de6c528f8caff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '8d92dd79149f29e89ee0f480254db595f6a6a2c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/psr-http-message-bridge' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '23a162bd446b93948a2c2f6909d80ad06195be10',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/psr-http-message-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '8a40d0f9b01f0fbb80885d3ce0ad6714fb603a58',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/serializer' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '56ce31d19127e79647ac53387c7555bdcd5730ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'bd1d9e59a81d8fa4acdcea3f617c581f7475a80f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/string' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '76792dbd99690a5ebef8050d9206c60c59e681d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'b9d2189887bb6b2e0367a9fc7136c5239ab9b05a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'ee0a4d6a327a963aee094f730da238f7ea18cb01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'c31566e4ca944271cc8d8ac6887cbf31b8c6a172',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'f9a060622e0d93777b7f8687ec4860191e16802e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '52903de178d542850f6f341ba92995d3d63e60c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v3.10.3',
            'version' => '3.10.3.0',
            'reference' => '67f29781ffafa520b0bbfbd8384674b42db04572',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webflo/drupal-finder' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '73045060b0894c77962a10cff047f72872d8810c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webflo/drupal-finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'a03d426c8e9fb2c9c569d9deeb31a083292788bc',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
